
# Let Argo CD manage itself
# We need to create an Application manifest that points to our "manually" installed Argo CD chart.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: {{ .Values.base.repoURL }}
      targetRevision: HEAD
      path: helm/argocd/ # N
    # - chart: argo-cd
    #   repoURL: https://argoproj.github.io/argo-helm
    #   targetRevision: 8.2.1
      helm:
        releaseName: argo
        valueFiles:
          - $values/helm/argocd/values.yaml
    - repoURL: {{ .Values.base.repoURL }}
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
