global:
  image:
    tag: v3.1.9  # Pin Argo CD app version for reproducibility

server:
  service:
    type: ClusterIP  # Avoid external LB cost until Post 4
  ingress:
    enabled: false

configs:
  params:
    server.insecure: true  # For local/dev use only
